const MARVEL_DATA = [
  {
    "id": 1,
    "title": "Blade",
    "release_date": "1998-08-21",
    "year": 1998,
    "type": "movie",
    "universe": "Blade universe / D&W connection",
    "category": "Legacy",
    "runtime_mins": 120,
    "watch_time": "2h 00m",
    "rating": "7.1/10",
    "trailer": "https://www.youtube.com/watch?v=kaU2LP4524U",
    "tmdb_id": 36647,
    "is_tv": false,
    "poster_portrait": "poster/portrait/1.webp",
    "poster_landscape": "poster/landscape/1.webp",
    "poster_portrait_fallback": "poster/portrait/1.jpg",
    "poster_landscape_fallback": "poster/landscape/1.jpg"
  },
  {
    "id": 2,
    "title": "X-Men",
    "release_date": "2000-07-14",
    "year": 2000,
    "type": "movie",
    "universe": "Fox",
    "category": "Fox",
    "runtime_mins": 104,
    "watch_time": "1h 44m",
    "rating": "7.3/10",
    "trailer": "https://www.youtube.com/watch?v=s4Wqw8tqgdM",
    "tmdb_id": 36657,
    "is_tv": false,
    "ddr_slug": "x-men-2000",
    "poster_portrait": "poster/portrait/2.webp",
    "poster_landscape": "poster/landscape/2.webp",
    "poster_portrait_fallback": "poster/portrait/2.jpg",
    "poster_landscape_fallback": "poster/landscape/2.jpg"
  },
  {
    "id": 3,
    "title": "Blade II",
    "release_date": "2002-03-22",
    "year": 2002,
    "type": "movie",
    "universe": "Blade universe / D&W connection",
    "category": "Legacy",
    "runtime_mins": 117,
    "watch_time": "1h 57m",
    "rating": "6.7/10",
    "trailer": "https://www.youtube.com/watch?v=4b2bUeHjP1o",
    "tmdb_id": 36586,
    "is_tv": false,
    "poster_portrait": "poster/portrait/3.webp",
    "poster_landscape": "poster/landscape/3.webp",
    "poster_portrait_fallback": "poster/portrait/3.jpg",
    "poster_landscape_fallback": "poster/landscape/3.jpg"
  },
  {
    "id": 4,
    "title": "Spider-Man",
    "release_date": "2002-05-03",
    "year": 2002,
    "type": "movie",
    "universe": "Raimi",
    "category": "Sony",
    "runtime_mins": 121,
    "watch_time": "2h 01m",
    "rating": "7.4/10",
    "trailer": "https://www.youtube.com/watch?v=t06RUxPbp_c",
    "tmdb_id": 557,
    "is_tv": false,
    "ddr_slug": "spider-man-2002",
    "poster_portrait": "poster/portrait/4.webp",
    "poster_landscape": "poster/landscape/4.webp",
    "poster_portrait_fallback": "poster/portrait/4.jpg",
    "poster_landscape_fallback": "poster/landscape/4.jpg"
  },
  {
    "id": 5,
    "title": "Daredevil",
    "release_date": "2003-02-14",
    "year": 2003,
    "type": "movie",
    "universe": "Daredevil/Elektra universe / D&W connection",
    "category": "Legacy",
    "runtime_mins": 103,
    "watch_time": "1h 43m",
    "rating": "5.3/10",
    "trailer": "https://www.youtube.com/watch?v=LmPRXWptUeg",
    "tmdb_id": 9480,
    "is_tv": false,
    "poster_portrait": "poster/portrait/5.webp",
    "poster_landscape": "poster/landscape/5.webp",
    "poster_portrait_fallback": "poster/portrait/5.jpg",
    "poster_landscape_fallback": "poster/landscape/5.jpg"
  },
  {
    "id": 6,
    "title": "X2: X-Men United",
    "release_date": "2003-05-02",
    "year": 2003,
    "type": "movie",
    "universe": "Fox",
    "category": "Fox",
    "runtime_mins": 134,
    "watch_time": "2h 14m",
    "rating": "7.4/10",
    "trailer": "https://www.youtube.com/watch?v=KjzPi5hfv9c",
    "tmdb_id": 36658,
    "is_tv": false,
    "ddr_slug": "x2",
    "poster_portrait": "poster/portrait/6.webp",
    "poster_landscape": "poster/landscape/6.webp",
    "poster_portrait_fallback": "poster/portrait/6.jpg",
    "poster_landscape_fallback": "poster/landscape/6.jpg"
  },
  {
    "id": 7,
    "title": "Hulk",
    "release_date": "2003-06-20",
    "year": 2003,
    "type": "movie",
    "universe": "Eric Bana universe / explicitly terminated in Endgame Encore",
    "category": "Legacy",
    "runtime_mins": 138,
    "watch_time": "2h 18m",
    "rating": "5.6/10",
    "trailer": "https://www.youtube.com/watch?v=xbqNb2PFKKA",
    "tmdb_id": 1927,
    "is_tv": false,
    "poster_portrait": "poster/portrait/7.webp",
    "poster_landscape": "poster/landscape/7.webp",
    "poster_portrait_fallback": "poster/portrait/7.jpg",
    "poster_landscape_fallback": "poster/landscape/7.jpg"
  },
  {
    "id": 8,
    "title": "The Punisher",
    "release_date": "2004-04-16",
    "year": 2004,
    "type": "movie",
    "universe": "Legacy Marvel film universe",
    "category": "Legacy",
    "runtime_mins": 124,
    "watch_time": "2h 04m",
    "rating": "6.4/10",
    "trailer": "https://www.youtube.com/watch?v=sW2w2b53j2c",
    "tmdb_id": 7220,
    "is_tv": false,
    "poster_portrait": "poster/portrait/8.webp",
    "poster_landscape": "poster/landscape/8.webp",
    "poster_portrait_fallback": "poster/portrait/8.jpg",
    "poster_landscape_fallback": "poster/landscape/8.jpg"
  },
  {
    "id": 9,
    "title": "Spider-Man 2",
    "release_date": "2004-06-30",
    "year": 2004,
    "type": "movie",
    "universe": "Raimi",
    "category": "Sony",
    "runtime_mins": 127,
    "watch_time": "2h 07m",
    "rating": "7.5/10",
    "trailer": "https://www.youtube.com/watch?v=CA5vsCnLm34",
    "tmdb_id": 558,
    "is_tv": false,
    "ddr_slug": "spider-man-2",
    "poster_portrait": "poster/portrait/9.webp",
    "poster_landscape": "poster/landscape/9.webp",
    "poster_portrait_fallback": "poster/portrait/9.jpg",
    "poster_landscape_fallback": "poster/landscape/9.jpg"
  },
  {
    "id": 10,
    "title": "Blade: Trinity",
    "release_date": "2004-12-08",
    "year": 2004,
    "type": "movie",
    "universe": "Blade universe / D&W connection",
    "category": "Legacy",
    "runtime_mins": 113,
    "watch_time": "1h 53m",
    "rating": "5.8/10",
    "trailer": "https://www.youtube.com/watch?v=A8FqG4gL6Fw",
    "tmdb_id": 36648,
    "is_tv": false,
    "poster_portrait": "poster/portrait/10.webp",
    "poster_landscape": "poster/landscape/10.webp",
    "poster_portrait_fallback": "poster/portrait/10.jpg",
    "poster_landscape_fallback": "poster/landscape/10.jpg"
  },
  {
    "id": 11,
    "title": "Elektra",
    "release_date": "2005-01-14",
    "year": 2005,
    "type": "movie",
    "universe": "Daredevil/Elektra universe / D&W connection",
    "category": "Legacy",
    "runtime_mins": 97,
    "watch_time": "1h 37m",
    "rating": "4.7/10",
    "trailer": "https://www.youtube.com/watch?v=B7bXkP3_Y0M",
    "tmdb_id": 9947,
    "is_tv": false,
    "poster_portrait": "poster/portrait/11.webp",
    "poster_landscape": "poster/landscape/11.webp",
    "poster_portrait_fallback": "poster/portrait/11.jpg",
    "poster_landscape_fallback": "poster/landscape/11.jpg"
  },
  {
    "id": 12,
    "title": "Fantastic Four",
    "release_date": "2005-07-08",
    "year": 2005,
    "type": "movie",
    "universe": "Fox / D&W connection",
    "category": "Fox",
    "runtime_mins": 106,
    "watch_time": "1h 46m",
    "rating": "5.7/10",
    "trailer": "https://www.youtube.com/watch?v=QIx2jkXYu34",
    "tmdb_id": 9738,
    "is_tv": false,
    "ddr_slug": "fantastic-four-2005",
    "poster_portrait": "poster/portrait/12.webp",
    "poster_landscape": "poster/landscape/12.webp",
    "poster_portrait_fallback": "poster/portrait/12.jpg",
    "poster_landscape_fallback": "poster/landscape/12.jpg"
  },
  {
    "id": 13,
    "title": "X-Men: The Last Stand",
    "release_date": "2006-05-26",
    "year": 2006,
    "type": "movie",
    "universe": "Fox",
    "category": "Fox",
    "runtime_mins": 104,
    "watch_time": "1h 44m",
    "rating": "6.6/10",
    "trailer": "https://www.youtube.com/watch?v=X8ozc_dQprk",
    "tmdb_id": 36668,
    "is_tv": false,
    "ddr_slug": "x-men-the-last-stand",
    "poster_portrait": "poster/portrait/13.webp",
    "poster_landscape": "poster/landscape/13.webp",
    "poster_portrait_fallback": "poster/portrait/13.jpg",
    "poster_landscape_fallback": "poster/landscape/13.jpg"
  },
  {
    "id": 14,
    "title": "Ghost Rider",
    "release_date": "2007-02-16",
    "year": 2007,
    "type": "movie",
    "universe": "Legacy Marvel film universe",
    "category": "Legacy",
    "runtime_mins": 110,
    "watch_time": "1h 50m",
    "rating": "5.3/10",
    "trailer": "https://www.youtube.com/watch?v=u3l3H4q5kX8",
    "tmdb_id": 1250,
    "is_tv": false,
    "poster_portrait": "poster/portrait/14.webp",
    "poster_landscape": "poster/landscape/14.webp",
    "poster_portrait_fallback": "poster/portrait/14.jpg",
    "poster_landscape_fallback": "poster/landscape/14.jpg"
  },
  {
    "id": 15,
    "title": "Spider-Man 3",
    "release_date": "2007-05-04",
    "year": 2007,
    "type": "movie",
    "universe": "Raimi",
    "category": "Sony",
    "runtime_mins": 139,
    "watch_time": "2h 19m",
    "rating": "6.3/10",
    "trailer": "https://www.youtube.com/watch?v=e5wUilOeOmg",
    "tmdb_id": 559,
    "is_tv": false,
    "ddr_slug": "spider-man-3",
    "poster_portrait": "poster/portrait/15.webp",
    "poster_landscape": "poster/landscape/15.webp",
    "poster_portrait_fallback": "poster/portrait/15.jpg",
    "poster_landscape_fallback": "poster/landscape/15.jpg"
  },
  {
    "id": 16,
    "title": "Fantastic Four: Rise of the Silver Surfer",
    "release_date": "2007-06-15",
    "year": 2007,
    "type": "movie",
    "universe": "Fox / D&W connection",
    "category": "Fox",
    "runtime_mins": 92,
    "watch_time": "1h 32m",
    "rating": "5.6/10",
    "trailer": "https://www.youtube.com/watch?v=7whodtti908",
    "tmdb_id": 1979,
    "is_tv": false,
    "ddr_slug": "fantastic-four-silver-surfer",
    "poster_portrait": "poster/portrait/16.webp",
    "poster_landscape": "poster/landscape/16.webp",
    "poster_portrait_fallback": "poster/portrait/16.jpg",
    "poster_landscape_fallback": "poster/landscape/16.jpg"
  },
  {
    "id": 17,
    "title": "Iron Man",
    "release_date": "2008-05-02",
    "year": 2008,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 126,
    "watch_time": "2h 06m",
    "rating": "7.9/10",
    "trailer": "https://www.youtube.com/watch?v=8ugaeA-nMTc",
    "tmdb_id": 1726,
    "is_tv": false,
    "ddr_slug": "iron-man",
    "poster_portrait": "poster/portrait/17.webp",
    "poster_landscape": "poster/landscape/17.webp",
    "poster_portrait_fallback": "poster/portrait/17.jpg",
    "poster_landscape_fallback": "poster/landscape/17.jpg"
  },
  {
    "id": 18,
    "title": "The Incredible Hulk",
    "release_date": "2008-06-13",
    "year": 2008,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 112,
    "watch_time": "1h 52m",
    "rating": "6.6/10",
    "trailer": "https://www.youtube.com/watch?v=dz6eBeW19Lg",
    "tmdb_id": 1724,
    "is_tv": false,
    "ddr_slug": "incredible-hulk",
    "poster_portrait": "poster/portrait/18.webp",
    "poster_landscape": "poster/landscape/18.webp",
    "poster_portrait_fallback": "poster/portrait/18.jpg",
    "poster_landscape_fallback": "poster/landscape/18.jpg"
  },
  {
    "id": 19,
    "title": "Punisher: War Zone",
    "release_date": "2008-12-05",
    "year": 2008,
    "type": "movie",
    "universe": "Legacy Marvel film universe",
    "category": "Legacy",
    "runtime_mins": 103,
    "watch_time": "1h 43m",
    "rating": "5.9/10",
    "trailer": "https://www.youtube.com/watch?v=f-B6QjT_k0o",
    "tmdb_id": 13056,
    "is_tv": false,
    "poster_portrait": "poster/portrait/19.webp",
    "poster_landscape": "poster/landscape/19.webp",
    "poster_portrait_fallback": "poster/portrait/19.jpg",
    "poster_landscape_fallback": "poster/landscape/19.jpg"
  },
  {
    "id": 20,
    "title": "X-Men Origins: Wolverine",
    "release_date": "2009-05-01",
    "year": 2009,
    "type": "movie",
    "universe": "Fox",
    "category": "Fox",
    "runtime_mins": 107,
    "watch_time": "1h 47m",
    "rating": "6.5/10",
    "trailer": "https://www.youtube.com/watch?v=kd6zYnHwQWA",
    "tmdb_id": 20662,
    "is_tv": false,
    "ddr_slug": "x-men-origins-wolverine",
    "poster_portrait": "poster/portrait/20.webp",
    "poster_landscape": "poster/landscape/20.webp",
    "poster_portrait_fallback": "poster/portrait/20.jpg",
    "poster_landscape_fallback": "poster/landscape/20.jpg"
  },
  {
    "id": 21,
    "title": "Iron Man 2",
    "release_date": "2010-05-07",
    "year": 2010,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 124,
    "watch_time": "2h 04m",
    "rating": "6.9/10",
    "trailer": "https://www.youtube.com/watch?v=5fUQkLdJ2kE",
    "tmdb_id": 10138,
    "is_tv": false,
    "ddr_slug": "iron-man-2",
    "poster_portrait": "poster/portrait/21.webp",
    "poster_landscape": "poster/landscape/21.webp",
    "poster_portrait_fallback": "poster/portrait/21.jpg",
    "poster_landscape_fallback": "poster/landscape/21.jpg"
  },
  {
    "id": 22,
    "title": "Thor",
    "release_date": "2011-05-06",
    "year": 2011,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 115,
    "watch_time": "1h 55m",
    "rating": "7.0/10",
    "trailer": "https://www.youtube.com/watch?v=uHBnrJowBZE",
    "tmdb_id": 10195,
    "is_tv": false,
    "ddr_slug": "thor",
    "poster_portrait": "poster/portrait/22.webp",
    "poster_landscape": "poster/landscape/22.webp",
    "poster_portrait_fallback": "poster/portrait/22.jpg",
    "poster_landscape_fallback": "poster/landscape/22.jpg"
  },
  {
    "id": 23,
    "title": "X-Men: First Class",
    "release_date": "2011-06-03",
    "year": 2011,
    "type": "movie",
    "universe": "Fox",
    "category": "Fox",
    "runtime_mins": 132,
    "watch_time": "2h 12m",
    "rating": "7.7/10",
    "trailer": "https://www.youtube.com/watch?v=s3w2b8b9j0c",
    "tmdb_id": 49538,
    "is_tv": false,
    "ddr_slug": "x-men-first-class",
    "poster_portrait": "poster/portrait/23.webp",
    "poster_landscape": "poster/landscape/23.webp",
    "poster_portrait_fallback": "poster/portrait/23.jpg",
    "poster_landscape_fallback": "poster/landscape/23.jpg"
  },
  {
    "id": 24,
    "title": "Captain America: The First Avenger",
    "release_date": "2011-07-22",
    "year": 2011,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 124,
    "watch_time": "2h 04m",
    "rating": "6.9/10",
    "trailer": "https://www.youtube.com/watch?v=JerVrbLldXw",
    "tmdb_id": 1771,
    "is_tv": false,
    "ddr_slug": "captain-america-the-first-avenger",
    "poster_portrait": "poster/portrait/24.webp",
    "poster_landscape": "poster/landscape/24.webp",
    "poster_portrait_fallback": "poster/portrait/24.jpg",
    "poster_landscape_fallback": "poster/landscape/24.jpg"
  },
  {
    "id": 25,
    "title": "Ghost Rider: Spirit of Vengeance",
    "release_date": "2012-02-17",
    "year": 2012,
    "type": "movie",
    "universe": "Legacy Marvel film universe",
    "category": "Legacy",
    "runtime_mins": 96,
    "watch_time": "1h 36m",
    "rating": "4.3/10",
    "trailer": "https://www.youtube.com/watch?v=ebCawfEnSWU",
    "tmdb_id": 71676,
    "is_tv": false,
    "poster_portrait": "poster/portrait/25.webp",
    "poster_landscape": "poster/landscape/25.webp",
    "poster_portrait_fallback": "poster/portrait/25.jpg",
    "poster_landscape_fallback": "poster/landscape/25.jpg"
  },
  {
    "id": 26,
    "title": "The Avengers",
    "release_date": "2012-05-04",
    "year": 2012,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 143,
    "watch_time": "2h 23m",
    "rating": "8.0/10",
    "trailer": "https://www.youtube.com/watch?v=eOrNdBpGMv8",
    "tmdb_id": 24428,
    "is_tv": false,
    "ddr_slug": "the-avengers",
    "poster_portrait": "poster/portrait/26.webp",
    "poster_landscape": "poster/landscape/26.webp",
    "poster_portrait_fallback": "poster/portrait/26.jpg",
    "poster_landscape_fallback": "poster/landscape/26.jpg"
  },
  {
    "id": 27,
    "title": "The Amazing Spider-Man",
    "release_date": "2012-07-03",
    "year": 2012,
    "type": "movie",
    "universe": "Sony/TASM",
    "category": "Sony",
    "runtime_mins": 136,
    "watch_time": "2h 16m",
    "rating": "6.9/10",
    "trailer": "https://www.youtube.com/watch?v=-tnxzJp54Yg",
    "tmdb_id": 1930,
    "is_tv": false,
    "ddr_slug": "amazing-spider-man",
    "poster_portrait": "poster/portrait/27.webp",
    "poster_landscape": "poster/landscape/27.webp",
    "poster_portrait_fallback": "poster/portrait/27.jpg",
    "poster_landscape_fallback": "poster/landscape/27.jpg"
  },
  {
    "id": 28,
    "title": "Iron Man 3",
    "release_date": "2013-05-03",
    "year": 2013,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 130,
    "watch_time": "2h 10m",
    "rating": "7.1/10",
    "trailer": "https://www.youtube.com/watch?v=YLorLVa95Xo",
    "tmdb_id": 68721,
    "is_tv": false,
    "ddr_slug": "iron-man-3",
    "poster_portrait": "poster/portrait/28.webp",
    "poster_landscape": "poster/landscape/28.webp",
    "poster_portrait_fallback": "poster/portrait/28.jpg",
    "poster_landscape_fallback": "poster/landscape/28.jpg"
  },
  {
    "id": 29,
    "title": "The Wolverine",
    "release_date": "2013-07-26",
    "year": 2013,
    "type": "movie",
    "universe": "Fox",
    "category": "Fox",
    "runtime_mins": 126,
    "watch_time": "2h 06m",
    "rating": "6.7/10",
    "trailer": "https://www.youtube.com/watch?v=th1ZPB2P5e4",
    "tmdb_id": 76170,
    "is_tv": false,
    "ddr_slug": "the-wolverine",
    "poster_portrait": "poster/portrait/29.webp",
    "poster_landscape": "poster/landscape/29.webp",
    "poster_portrait_fallback": "poster/portrait/29.jpg",
    "poster_landscape_fallback": "poster/landscape/29.jpg"
  },
  {
    "id": 30,
    "title": "Thor: The Dark World",
    "release_date": "2013-11-08",
    "year": 2013,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 112,
    "watch_time": "1h 52m",
    "rating": "6.8/10",
    "trailer": "https://www.youtube.com/watch?v=npvJ9FTgZbM",
    "tmdb_id": 76338,
    "is_tv": false,
    "ddr_slug": "thor-the-dark-world",
    "poster_portrait": "poster/portrait/30.webp",
    "poster_landscape": "poster/landscape/30.webp",
    "poster_portrait_fallback": "poster/portrait/30.jpg",
    "poster_landscape_fallback": "poster/landscape/30.jpg"
  },
  {
    "id": 31,
    "title": "Captain America: The Winter Soldier",
    "release_date": "2014-04-04",
    "year": 2014,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 136,
    "watch_time": "2h 16m",
    "rating": "7.8/10",
    "trailer": "https://www.youtube.com/watch?v=7SlILk2WMTI",
    "tmdb_id": 100402,
    "is_tv": false,
    "ddr_slug": "captain-america-the-winter-soldier",
    "poster_portrait": "poster/portrait/31.webp",
    "poster_landscape": "poster/landscape/31.webp",
    "poster_portrait_fallback": "poster/portrait/31.jpg",
    "poster_landscape_fallback": "poster/landscape/31.jpg"
  },
  {
    "id": 32,
    "title": "The Amazing Spider-Man 2",
    "release_date": "2014-05-02",
    "year": 2014,
    "type": "movie",
    "universe": "Sony/TASM",
    "category": "Sony",
    "runtime_mins": 142,
    "watch_time": "2h 22m",
    "rating": "6.6/10",
    "trailer": "https://www.youtube.com/watch?v=nbp3Ra3YpCE",
    "tmdb_id": 102382,
    "is_tv": false,
    "ddr_slug": "amazing-spider-man-2",
    "poster_portrait": "poster/portrait/32.webp",
    "poster_landscape": "poster/landscape/32.webp",
    "poster_portrait_fallback": "poster/portrait/32.jpg",
    "poster_landscape_fallback": "poster/landscape/32.jpg"
  },
  {
    "id": 33,
    "title": "X-Men: Days of Future Past",
    "release_date": "2014-05-23",
    "year": 2014,
    "type": "movie",
    "universe": "Fox",
    "category": "Fox",
    "runtime_mins": 132,
    "watch_time": "2h 12m",
    "rating": "7.9/10",
    "trailer": "https://www.youtube.com/watch?v=pK2zYHWDZKo",
    "tmdb_id": 127585,
    "is_tv": false,
    "ddr_slug": "x-men-days-of-future-past",
    "poster_portrait": "poster/portrait/33.webp",
    "poster_landscape": "poster/landscape/33.webp",
    "poster_portrait_fallback": "poster/portrait/33.jpg",
    "poster_landscape_fallback": "poster/landscape/33.jpg"
  },
  {
    "id": 34,
    "title": "Guardians of the Galaxy",
    "release_date": "2014-08-01",
    "year": 2014,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 121,
    "watch_time": "2h 01m",
    "rating": "8.0/10",
    "trailer": "https://www.youtube.com/watch?v=d96cjJhvlMA",
    "tmdb_id": 118340,
    "is_tv": false,
    "ddr_slug": "guardians-of-the-galaxy",
    "poster_portrait": "poster/portrait/34.webp",
    "poster_landscape": "poster/landscape/34.webp",
    "poster_portrait_fallback": "poster/portrait/34.jpg",
    "poster_landscape_fallback": "poster/landscape/34.jpg"
  },
  {
    "id": 35,
    "title": "Daredevil \u2014 Season 1",
    "release_date": "2015-04-10",
    "year": 2015,
    "type": "series",
    "universe": "Defenders/MCU-adjacent",
    "category": "Defenders",
    "runtime_mins": 702,
    "total_watch_time": "11h 42m",
    "avg_watch_time": "54m / ep",
    "episodes": 13,
    "rating": "8.6/10",
    "trailer": "https://www.youtube.com/watch?v=jAy6NJ_D5vU",
    "tmdb_id": 61889,
    "is_tv": true,
    "ddr_slug": "daredevil-s1",
    "poster_portrait": "poster/portrait/35.webp",
    "poster_landscape": "poster/landscape/35.webp",
    "poster_portrait_fallback": "poster/portrait/35.jpg",
    "poster_landscape_fallback": "poster/landscape/35.jpg"
  },
  {
    "id": 36,
    "title": "Avengers: Age of Ultron",
    "release_date": "2015-05-01",
    "year": 2015,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 141,
    "watch_time": "2h 21m",
    "rating": "7.3/10",
    "trailer": "https://www.youtube.com/watch?v=tmeOjFno6Do",
    "tmdb_id": 99861,
    "is_tv": false,
    "ddr_slug": "avengers-age-of-ultron",
    "poster_portrait": "poster/portrait/36.webp",
    "poster_landscape": "poster/landscape/36.webp",
    "poster_portrait_fallback": "poster/portrait/36.jpg",
    "poster_landscape_fallback": "poster/landscape/36.jpg"
  },
  {
    "id": 37,
    "title": "Ant-Man",
    "release_date": "2015-07-17",
    "year": 2015,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 117,
    "watch_time": "1h 57m",
    "rating": "7.2/10",
    "trailer": "https://www.youtube.com/watch?v=pWdKf3MneyI",
    "tmdb_id": 102899,
    "is_tv": false,
    "ddr_slug": "ant-man",
    "poster_portrait": "poster/portrait/37.webp",
    "poster_landscape": "poster/landscape/37.webp",
    "poster_portrait_fallback": "poster/portrait/37.jpg",
    "poster_landscape_fallback": "poster/landscape/37.jpg"
  },
  {
    "id": 38,
    "title": "Fantastic Four",
    "release_date": "2015-08-07",
    "year": 2015,
    "type": "movie",
    "universe": "2015 Fox universe / explicitly terminated in Endgame Encore",
    "category": "Fox",
    "runtime_mins": 100,
    "watch_time": "1h 40m",
    "rating": "4.3/10",
    "trailer": "https://www.youtube.com/watch?v=_rRoD28-WgU",
    "tmdb_id": 166424,
    "is_tv": false,
    "ddr_slug": "fantastic-four-2015",
    "poster_portrait": "poster/portrait/38.webp",
    "poster_landscape": "poster/landscape/38.webp",
    "poster_portrait_fallback": "poster/portrait/38.jpg",
    "poster_landscape_fallback": "poster/landscape/38.jpg"
  },
  {
    "id": 39,
    "title": "Jessica Jones \u2014 Season 1",
    "release_date": "2015-11-20",
    "year": 2015,
    "type": "series",
    "universe": "Defenders",
    "category": "Defenders",
    "runtime_mins": 676,
    "total_watch_time": "11h 16m",
    "avg_watch_time": "52m / ep",
    "episodes": 13,
    "rating": "7.9/10",
    "trailer": "https://www.youtube.com/watch?v=s3UYWK21ug0",
    "tmdb_id": 38472,
    "is_tv": true,
    "poster_portrait": "poster/portrait/39.webp",
    "poster_landscape": "poster/landscape/39.webp",
    "poster_portrait_fallback": "poster/portrait/39.jpg",
    "poster_landscape_fallback": "poster/landscape/39.jpg"
  },
  {
    "id": 40,
    "title": "Deadpool",
    "release_date": "2016-02-12",
    "year": 2016,
    "type": "movie",
    "universe": "Fox / Earth-10005",
    "category": "Fox",
    "runtime_mins": 108,
    "watch_time": "1h 48m",
    "rating": "8.0/10",
    "trailer": "https://www.youtube.com/watch?v=FyKWUTwSYAs",
    "tmdb_id": 293660,
    "is_tv": false,
    "ddr_slug": "deadpool",
    "poster_portrait": "poster/portrait/40.webp",
    "poster_landscape": "poster/landscape/40.webp",
    "poster_portrait_fallback": "poster/portrait/40.jpg",
    "poster_landscape_fallback": "poster/landscape/40.jpg"
  },
  {
    "id": 41,
    "title": "Daredevil \u2014 Season 2",
    "release_date": "2016-03-18",
    "year": 2016,
    "type": "series",
    "universe": "Defenders",
    "category": "Defenders",
    "runtime_mins": 702,
    "total_watch_time": "11h 42m",
    "avg_watch_time": "54m / ep",
    "episodes": 13,
    "rating": "8.6/10",
    "trailer": "https://www.youtube.com/watch?v=2Cw3320_pLA",
    "tmdb_id": 61889,
    "is_tv": true,
    "ddr_slug": "daredevil-s2",
    "poster_portrait": "poster/portrait/41.webp",
    "poster_landscape": "poster/landscape/41.webp",
    "poster_portrait_fallback": "poster/portrait/41.jpg",
    "poster_landscape_fallback": "poster/landscape/41.jpg"
  },
  {
    "id": 42,
    "title": "Captain America: Civil War",
    "release_date": "2016-05-06",
    "year": 2016,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 147,
    "watch_time": "2h 27m",
    "rating": "7.8/10",
    "trailer": "https://www.youtube.com/watch?v=dKrVegVI0Us",
    "tmdb_id": 271110,
    "is_tv": false,
    "ddr_slug": "captain-america-civil-war",
    "poster_portrait": "poster/portrait/42.webp",
    "poster_landscape": "poster/landscape/42.webp",
    "poster_portrait_fallback": "poster/portrait/42.jpg",
    "poster_landscape_fallback": "poster/landscape/42.jpg"
  },
  {
    "id": 43,
    "title": "X-Men: Apocalypse",
    "release_date": "2016-05-27",
    "year": 2016,
    "type": "movie",
    "universe": "Fox",
    "category": "Fox",
    "runtime_mins": 144,
    "watch_time": "2h 24m",
    "rating": "6.9/10",
    "trailer": "https://www.youtube.com/watch?v=COvnHv437-o",
    "tmdb_id": 246655,
    "is_tv": false,
    "ddr_slug": "x-men-apocalypse",
    "poster_portrait": "poster/portrait/43.webp",
    "poster_landscape": "poster/landscape/43.webp",
    "poster_portrait_fallback": "poster/portrait/43.jpg",
    "poster_landscape_fallback": "poster/landscape/43.jpg"
  },
  {
    "id": 44,
    "title": "Luke Cage \u2014 Season 1",
    "release_date": "2016-09-30",
    "year": 2016,
    "type": "series",
    "universe": "Defenders",
    "category": "Defenders",
    "runtime_mins": 715,
    "total_watch_time": "11h 55m",
    "avg_watch_time": "55m / ep",
    "episodes": 13,
    "rating": "7.3/10",
    "trailer": "https://www.youtube.com/watch?v=snJ-nRgx8o0",
    "tmdb_id": 67070,
    "is_tv": true,
    "poster_portrait": "poster/portrait/44.webp",
    "poster_landscape": "poster/landscape/44.webp",
    "poster_portrait_fallback": "poster/portrait/44.jpg",
    "poster_landscape_fallback": "poster/landscape/44.jpg"
  },
  {
    "id": 45,
    "title": "Doctor Strange",
    "release_date": "2016-11-04",
    "year": 2016,
    "type": "movie",
    "universe": "MCU / multiverse foundation",
    "category": "MCU",
    "runtime_mins": 115,
    "watch_time": "1h 55m",
    "rating": "7.5/10",
    "trailer": "https://www.youtube.com/watch?v=HSzx-zryEgM",
    "tmdb_id": 284052,
    "is_tv": false,
    "ddr_slug": "doctor-strange",
    "poster_portrait": "poster/portrait/45.webp",
    "poster_landscape": "poster/landscape/45.webp",
    "poster_portrait_fallback": "poster/portrait/45.jpg",
    "poster_landscape_fallback": "poster/landscape/45.jpg"
  },
  {
    "id": 46,
    "title": "Logan",
    "release_date": "2017-03-03",
    "year": 2017,
    "type": "movie",
    "universe": "Fox",
    "category": "Fox",
    "runtime_mins": 137,
    "watch_time": "2h 17m",
    "rating": "8.1/10",
    "trailer": "https://www.youtube.com/watch?v=Div0iP65aZo",
    "tmdb_id": 263115,
    "is_tv": false,
    "ddr_slug": "logan",
    "poster_portrait": "poster/portrait/46.webp",
    "poster_landscape": "poster/landscape/46.webp",
    "poster_portrait_fallback": "poster/portrait/46.jpg",
    "poster_landscape_fallback": "poster/landscape/46.jpg"
  },
  {
    "id": 47,
    "title": "Iron Fist \u2014 Season 1",
    "release_date": "2017-03-17",
    "year": 2017,
    "type": "series",
    "universe": "Defenders",
    "category": "Defenders",
    "runtime_mins": 728,
    "total_watch_time": "12h 08m",
    "avg_watch_time": "56m / ep",
    "episodes": 13,
    "rating": "6.4/10",
    "trailer": "https://www.youtube.com/watch?v=0sE68w68_bY",
    "tmdb_id": 62127,
    "is_tv": true,
    "poster_portrait": "poster/portrait/47.webp",
    "poster_landscape": "poster/landscape/47.webp",
    "poster_portrait_fallback": "poster/portrait/47.jpg",
    "poster_landscape_fallback": "poster/landscape/47.jpg"
  },
  {
    "id": 48,
    "title": "Guardians of the Galaxy Vol. 2",
    "release_date": "2017-05-05",
    "year": 2017,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 136,
    "watch_time": "2h 16m",
    "rating": "7.6/10",
    "trailer": "https://www.youtube.com/watch?v=dW1BIid8Osg",
    "tmdb_id": 283995,
    "is_tv": false,
    "ddr_slug": "guardians-of-the-galaxy-vol-2",
    "poster_portrait": "poster/portrait/48.webp",
    "poster_landscape": "poster/landscape/48.webp",
    "poster_portrait_fallback": "poster/portrait/48.jpg",
    "poster_landscape_fallback": "poster/landscape/48.jpg"
  },
  {
    "id": 49,
    "title": "Spider-Man: Homecoming",
    "release_date": "2017-07-07",
    "year": 2017,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 133,
    "watch_time": "2h 13m",
    "rating": "7.4/10",
    "trailer": "https://www.youtube.com/watch?v=rk-dF1lIbIg",
    "tmdb_id": 315635,
    "is_tv": false,
    "ddr_slug": "spider-man-homecoming",
    "poster_portrait": "poster/portrait/49.webp",
    "poster_landscape": "poster/landscape/49.webp",
    "poster_portrait_fallback": "poster/portrait/49.jpg",
    "poster_landscape_fallback": "poster/landscape/49.jpg"
  },
  {
    "id": 50,
    "title": "The Defenders",
    "release_date": "2017-08-18",
    "year": 2017,
    "type": "series",
    "universe": "Defenders",
    "category": "Defenders",
    "runtime_mins": 400,
    "total_watch_time": "6h 40m",
    "avg_watch_time": "50m / ep",
    "episodes": 8,
    "rating": "7.2/10",
    "trailer": "https://www.youtube.com/watch?v=4h3m7B4v6Zc",
    "tmdb_id": 62285,
    "is_tv": true,
    "ddr_slug": "defenders",
    "poster_portrait": "poster/portrait/50.webp",
    "poster_landscape": "poster/landscape/50.webp",
    "poster_portrait_fallback": "poster/portrait/50.jpg",
    "poster_landscape_fallback": "poster/landscape/50.jpg"
  },
  {
    "id": 51,
    "title": "Thor: Ragnarok",
    "release_date": "2017-11-03",
    "year": 2017,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 130,
    "watch_time": "2h 10m",
    "rating": "7.9/10",
    "trailer": "https://www.youtube.com/watch?v=ue80QwXMRHg",
    "tmdb_id": 284053,
    "is_tv": false,
    "ddr_slug": "thor-ragnarok",
    "poster_portrait": "poster/portrait/51.webp",
    "poster_landscape": "poster/landscape/51.webp",
    "poster_portrait_fallback": "poster/portrait/51.jpg",
    "poster_landscape_fallback": "poster/landscape/51.jpg"
  },
  {
    "id": 52,
    "title": "The Punisher \u2014 Season 1",
    "release_date": "2017-11-17",
    "year": 2017,
    "type": "series",
    "universe": "Defenders",
    "category": "Defenders",
    "runtime_mins": 689,
    "total_watch_time": "11h 29m",
    "avg_watch_time": "53m / ep",
    "episodes": 13,
    "rating": "8.5/10",
    "trailer": "https://www.youtube.com/watch?v=OMW_dP695Jg",
    "tmdb_id": 67178,
    "is_tv": true,
    "ddr_slug": "punisher-s1",
    "poster_portrait": "poster/portrait/52.webp",
    "poster_landscape": "poster/landscape/52.webp",
    "poster_portrait_fallback": "poster/portrait/52.jpg",
    "poster_landscape_fallback": "poster/landscape/52.jpg"
  },
  {
    "id": 53,
    "title": "Black Panther",
    "release_date": "2018-02-16",
    "year": 2018,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 134,
    "watch_time": "2h 14m",
    "rating": "7.3/10",
    "trailer": "https://www.youtube.com/watch?v=xjDjIWPwcPU",
    "tmdb_id": 284054,
    "is_tv": false,
    "ddr_slug": "black-panther",
    "poster_portrait": "poster/portrait/53.webp",
    "poster_landscape": "poster/landscape/53.webp",
    "poster_portrait_fallback": "poster/portrait/53.jpg",
    "poster_landscape_fallback": "poster/landscape/53.jpg"
  },
  {
    "id": 54,
    "title": "Jessica Jones \u2014 Season 2",
    "release_date": "2018-03-08",
    "year": 2018,
    "type": "series",
    "universe": "Defenders",
    "category": "Defenders",
    "runtime_mins": 663,
    "total_watch_time": "11h 03m",
    "avg_watch_time": "51m / ep",
    "episodes": 13,
    "rating": "7.9/10",
    "trailer": "https://www.youtube.com/watch?v=SLkX_fB5F6Y",
    "tmdb_id": 38472,
    "is_tv": true,
    "poster_portrait": "poster/portrait/54.webp",
    "poster_landscape": "poster/landscape/54.webp",
    "poster_portrait_fallback": "poster/portrait/54.jpg",
    "poster_landscape_fallback": "poster/landscape/54.jpg"
  },
  {
    "id": 55,
    "title": "Avengers: Infinity War",
    "release_date": "2018-04-27",
    "year": 2018,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 149,
    "watch_time": "2h 29m",
    "rating": "8.4/10",
    "trailer": "https://www.youtube.com/watch?v=6ZfuNTqbHE8",
    "tmdb_id": 299536,
    "is_tv": false,
    "ddr_slug": "avengers-infinity-war",
    "poster_portrait": "poster/portrait/55.webp",
    "poster_landscape": "poster/landscape/55.webp",
    "poster_portrait_fallback": "poster/portrait/55.jpg",
    "poster_landscape_fallback": "poster/landscape/55.jpg"
  },
  {
    "id": 56,
    "title": "Deadpool 2",
    "release_date": "2018-05-18",
    "year": 2018,
    "type": "movie",
    "universe": "Fox",
    "category": "Fox",
    "runtime_mins": 119,
    "watch_time": "1h 59m",
    "rating": "7.6/10",
    "trailer": "https://www.youtube.com/watch?v=D86RtevtfrA",
    "tmdb_id": 383498,
    "is_tv": false,
    "ddr_slug": "deadpool-2",
    "poster_portrait": "poster/portrait/56.webp",
    "poster_landscape": "poster/landscape/56.webp",
    "poster_portrait_fallback": "poster/portrait/56.jpg",
    "poster_landscape_fallback": "poster/landscape/56.jpg"
  },
  {
    "id": 57,
    "title": "Luke Cage \u2014 Season 2",
    "release_date": "2018-06-22",
    "year": 2018,
    "type": "series",
    "universe": "Defenders",
    "category": "Defenders",
    "runtime_mins": 728,
    "total_watch_time": "12h 08m",
    "avg_watch_time": "56m / ep",
    "episodes": 13,
    "rating": "7.3/10",
    "trailer": "https://www.youtube.com/watch?v=sB1in0KkAJE",
    "tmdb_id": 67070,
    "is_tv": true,
    "poster_portrait": "poster/portrait/57.webp",
    "poster_landscape": "poster/landscape/57.webp",
    "poster_portrait_fallback": "poster/portrait/57.jpg",
    "poster_landscape_fallback": "poster/landscape/57.jpg"
  },
  {
    "id": 58,
    "title": "Ant-Man and the Wasp",
    "release_date": "2018-07-06",
    "year": 2018,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 118,
    "watch_time": "1h 58m",
    "rating": "7.0/10",
    "trailer": "https://www.youtube.com/watch?v=8_rTIAOohas",
    "tmdb_id": 363088,
    "is_tv": false,
    "ddr_slug": "ant-man-and-the-wasp",
    "poster_portrait": "poster/portrait/58.webp",
    "poster_landscape": "poster/landscape/58.webp",
    "poster_portrait_fallback": "poster/portrait/58.jpg",
    "poster_landscape_fallback": "poster/landscape/58.jpg"
  },
  {
    "id": 59,
    "title": "Iron Fist \u2014 Season 2",
    "release_date": "2018-09-07",
    "year": 2018,
    "type": "series",
    "universe": "Defenders",
    "category": "Defenders",
    "runtime_mins": 510,
    "total_watch_time": "8h 30m",
    "avg_watch_time": "51m / ep",
    "episodes": 10,
    "rating": "6.4/10",
    "trailer": "https://www.youtube.com/watch?v=4y3gHjM6r9I",
    "tmdb_id": 62127,
    "is_tv": true,
    "poster_portrait": "poster/portrait/59.webp",
    "poster_landscape": "poster/landscape/59.webp",
    "poster_portrait_fallback": "poster/portrait/59.jpg",
    "poster_landscape_fallback": "poster/landscape/59.jpg"
  },
  {
    "id": 60,
    "title": "Venom",
    "release_date": "2018-10-05",
    "year": 2018,
    "type": "movie",
    "universe": "Sony's Spider-Man Universe",
    "category": "Sony",
    "runtime_mins": 112,
    "watch_time": "1h 52m",
    "rating": "6.6/10",
    "trailer": "https://www.youtube.com/watch?v=u9Mv98Gr5pY",
    "tmdb_id": 335983,
    "is_tv": false,
    "poster_portrait": "poster/portrait/60.webp",
    "poster_landscape": "poster/landscape/60.webp",
    "poster_portrait_fallback": "poster/portrait/60.jpg",
    "poster_landscape_fallback": "poster/landscape/60.jpg"
  },
  {
    "id": 61,
    "title": "Daredevil \u2014 Season 3",
    "release_date": "2018-10-19",
    "year": 2018,
    "type": "series",
    "universe": "Defenders",
    "category": "Defenders",
    "runtime_mins": 702,
    "total_watch_time": "11h 42m",
    "avg_watch_time": "54m / ep",
    "episodes": 13,
    "rating": "8.6/10",
    "trailer": "https://www.youtube.com/watch?v=n83s6NO1NE0",
    "tmdb_id": 61889,
    "is_tv": true,
    "ddr_slug": "daredevil-s3",
    "poster_portrait": "poster/portrait/61.webp",
    "poster_landscape": "poster/landscape/61.webp",
    "poster_portrait_fallback": "poster/portrait/61.jpg",
    "poster_landscape_fallback": "poster/landscape/61.jpg"
  },
  {
    "id": 62,
    "title": "Spider-Man: Into the Spider-Verse",
    "release_date": "2018-12-14",
    "year": 2018,
    "type": "movie",
    "universe": "Sony/animated multiverse",
    "category": "Sony",
    "runtime_mins": 117,
    "watch_time": "1h 57m",
    "rating": "8.4/10",
    "trailer": "https://www.youtube.com/watch?v=tg52up16eq0",
    "tmdb_id": 324857,
    "is_tv": false,
    "poster_portrait": "poster/portrait/62.webp",
    "poster_landscape": "poster/landscape/62.webp",
    "poster_portrait_fallback": "poster/portrait/62.jpg",
    "poster_landscape_fallback": "poster/landscape/62.jpg"
  },
  {
    "id": 63,
    "title": "The Punisher \u2014 Season 2",
    "release_date": "2019-01-18",
    "year": 2019,
    "type": "series",
    "universe": "Defenders",
    "category": "Defenders",
    "runtime_mins": 689,
    "total_watch_time": "11h 29m",
    "avg_watch_time": "53m / ep",
    "episodes": 13,
    "rating": "8.5/10",
    "trailer": "https://www.youtube.com/watch?v=jrLhP5sK2wI",
    "tmdb_id": 67178,
    "is_tv": true,
    "ddr_slug": "punisher-s2",
    "poster_portrait": "poster/portrait/63.webp",
    "poster_landscape": "poster/landscape/63.webp",
    "poster_portrait_fallback": "poster/portrait/63.jpg",
    "poster_landscape_fallback": "poster/landscape/63.jpg"
  },
  {
    "id": 64,
    "title": "Captain Marvel",
    "release_date": "2019-03-08",
    "year": 2019,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 124,
    "watch_time": "2h 04m",
    "rating": "6.8/10",
    "trailer": "https://www.youtube.com/watch?v=Z1BCujX3pw8",
    "tmdb_id": 299537,
    "is_tv": false,
    "ddr_slug": "captain-marvel",
    "poster_portrait": "poster/portrait/64.webp",
    "poster_landscape": "poster/landscape/64.webp",
    "poster_portrait_fallback": "poster/portrait/64.jpg",
    "poster_landscape_fallback": "poster/landscape/64.jpg"
  },
  {
    "id": 65,
    "title": "Avengers: Endgame",
    "release_date": "2019-04-26",
    "year": 2019,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 181,
    "watch_time": "3h 01m",
    "rating": "8.4/10",
    "trailer": "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    "tmdb_id": 299534,
    "is_tv": false,
    "ddr_slug": "avengers-endgame",
    "poster_portrait": "poster/portrait/65.webp",
    "poster_landscape": "poster/landscape/65.webp",
    "poster_portrait_fallback": "poster/portrait/65.jpg",
    "poster_landscape_fallback": "poster/landscape/65.jpg"
  },
  {
    "id": 66,
    "title": "Dark Phoenix",
    "release_date": "2019-06-07",
    "year": 2019,
    "type": "movie",
    "universe": "Fox",
    "category": "Fox",
    "runtime_mins": 113,
    "watch_time": "1h 53m",
    "rating": "5.7/10",
    "trailer": "https://www.youtube.com/watch?v=1-q8C_c-nlM",
    "tmdb_id": 320288,
    "is_tv": false,
    "ddr_slug": "dark-phoenix",
    "poster_portrait": "poster/portrait/66.webp",
    "poster_landscape": "poster/landscape/66.webp",
    "poster_portrait_fallback": "poster/portrait/66.jpg",
    "poster_landscape_fallback": "poster/landscape/66.jpg"
  },
  {
    "id": 67,
    "title": "Jessica Jones \u2014 Season 3",
    "release_date": "2019-06-14",
    "year": 2019,
    "type": "series",
    "universe": "Defenders",
    "category": "Defenders",
    "runtime_mins": 676,
    "total_watch_time": "11h 16m",
    "avg_watch_time": "52m / ep",
    "episodes": 13,
    "rating": "7.9/10",
    "trailer": "https://www.youtube.com/watch?v=34Uv2_9v2i4",
    "tmdb_id": 38472,
    "is_tv": true,
    "poster_portrait": "poster/portrait/67.webp",
    "poster_landscape": "poster/landscape/67.webp",
    "poster_portrait_fallback": "poster/portrait/67.jpg",
    "poster_landscape_fallback": "poster/landscape/67.jpg"
  },
  {
    "id": 68,
    "title": "Spider-Man: Far From Home",
    "release_date": "2019-07-02",
    "year": 2019,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 129,
    "watch_time": "2h 09m",
    "rating": "7.4/10",
    "trailer": "https://www.youtube.com/watch?v=Nt9L1jCKGnE",
    "tmdb_id": 429617,
    "is_tv": false,
    "ddr_slug": "spider-man-far-from-home",
    "poster_portrait": "poster/portrait/68.webp",
    "poster_landscape": "poster/landscape/68.webp",
    "poster_portrait_fallback": "poster/portrait/68.jpg",
    "poster_landscape_fallback": "poster/landscape/68.jpg"
  },
  {
    "id": 69,
    "title": "The New Mutants",
    "release_date": "2020-08-28",
    "year": 2020,
    "type": "movie",
    "universe": "Fox",
    "category": "Fox",
    "runtime_mins": 94,
    "watch_time": "1h 34m",
    "rating": "5.3/10",
    "trailer": "https://www.youtube.com/watch?v=W_vJhUA3dHY",
    "tmdb_id": 340102,
    "is_tv": false,
    "ddr_slug": "new-mutants",
    "poster_portrait": "poster/portrait/69.webp",
    "poster_landscape": "poster/landscape/69.webp",
    "poster_portrait_fallback": "poster/portrait/69.jpg",
    "poster_landscape_fallback": "poster/landscape/69.jpg"
  },
  {
    "id": 70,
    "title": "WandaVision",
    "release_date": "2021-01-15",
    "year": 2021,
    "type": "series",
    "universe": "MCU / multiverse",
    "category": "MCU",
    "runtime_mins": 351,
    "total_watch_time": "5h 51m",
    "avg_watch_time": "39m / ep",
    "episodes": 9,
    "rating": "7.9/10",
    "trailer": "https://www.youtube.com/watch?v=UBhlqe2KVt4",
    "tmdb_id": 85271,
    "is_tv": true,
    "ddr_slug": "wandavision",
    "poster_portrait": "poster/portrait/70.webp",
    "poster_landscape": "poster/landscape/70.webp",
    "poster_portrait_fallback": "poster/portrait/70.jpg",
    "poster_landscape_fallback": "poster/landscape/70.jpg"
  },
  {
    "id": 71,
    "title": "The Falcon and the Winter Soldier",
    "release_date": "2021-03-19",
    "year": 2021,
    "type": "series",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 306,
    "total_watch_time": "5h 06m",
    "avg_watch_time": "51m / ep",
    "episodes": 6,
    "rating": "7.1/10",
    "trailer": "https://www.youtube.com/watch?v=IWBsDaFWyTE",
    "tmdb_id": 88396,
    "is_tv": true,
    "ddr_slug": "falcon-and-winter-soldier",
    "poster_portrait": "poster/portrait/71.webp",
    "poster_landscape": "poster/landscape/71.webp",
    "poster_portrait_fallback": "poster/portrait/71.jpg",
    "poster_landscape_fallback": "poster/landscape/71.jpg"
  },
  {
    "id": 72,
    "title": "Loki \u2014 Season 1",
    "release_date": "2021-06-09",
    "year": 2021,
    "type": "series",
    "universe": "TVA / multiverse",
    "category": "MCU",
    "runtime_mins": 300,
    "total_watch_time": "5h 00m",
    "avg_watch_time": "50m / ep",
    "episodes": 6,
    "rating": "8.2/10",
    "trailer": "https://www.youtube.com/watch?v=nW948Va-l10",
    "tmdb_id": 84958,
    "is_tv": true,
    "ddr_slug": "loki-s1",
    "poster_portrait": "poster/portrait/72.webp",
    "poster_landscape": "poster/landscape/72.webp",
    "poster_portrait_fallback": "poster/portrait/72.jpg",
    "poster_landscape_fallback": "poster/landscape/72.jpg"
  },
  {
    "id": 73,
    "title": "Black Widow",
    "release_date": "2021-07-09",
    "year": 2021,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 134,
    "watch_time": "2h 14m",
    "rating": "6.7/10",
    "trailer": "https://www.youtube.com/watch?v=Fp9pNPdNwjI",
    "tmdb_id": 497698,
    "is_tv": false,
    "ddr_slug": "black-widow",
    "poster_portrait": "poster/portrait/73.webp",
    "poster_landscape": "poster/landscape/73.webp",
    "poster_portrait_fallback": "poster/portrait/73.jpg",
    "poster_landscape_fallback": "poster/landscape/73.jpg"
  },
  {
    "id": 74,
    "title": "What If...? \u2014 Season 1",
    "release_date": "2021-08-11",
    "year": 2021,
    "type": "series",
    "universe": "Animated multiverse",
    "category": "MCU",
    "runtime_mins": 306,
    "total_watch_time": "5h 06m",
    "avg_watch_time": "34m / ep",
    "episodes": 9,
    "rating": "7.4/10",
    "trailer": "https://www.youtube.com/watch?v=x9D0uUKJ5KI",
    "tmdb_id": 91363,
    "is_tv": true,
    "ddr_slug": "what-if-s1",
    "poster_portrait": "poster/portrait/74.webp",
    "poster_landscape": "poster/landscape/74.webp",
    "poster_portrait_fallback": "poster/portrait/74.jpg",
    "poster_landscape_fallback": "poster/landscape/74.jpg"
  },
  {
    "id": 75,
    "title": "Shang-Chi and the Legend of the Ten Rings",
    "release_date": "2021-09-03",
    "year": 2021,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 132,
    "watch_time": "2h 12m",
    "rating": "7.4/10",
    "trailer": "https://www.youtube.com/watch?v=8YjFbMbfXaQ",
    "tmdb_id": 566525,
    "is_tv": false,
    "ddr_slug": "shang-chi",
    "poster_portrait": "poster/portrait/75.webp",
    "poster_landscape": "poster/landscape/75.webp",
    "poster_portrait_fallback": "poster/portrait/75.jpg",
    "poster_landscape_fallback": "poster/landscape/75.jpg"
  },
  {
    "id": 76,
    "title": "Venom: Let There Be Carnage",
    "release_date": "2021-10-01",
    "year": 2021,
    "type": "movie",
    "universe": "Sony's Spider-Man Universe",
    "category": "Sony",
    "runtime_mins": 97,
    "watch_time": "1h 37m",
    "rating": "5.9/10",
    "trailer": "https://www.youtube.com/watch?v=-FmWuCgJmxo",
    "tmdb_id": 580489,
    "is_tv": false,
    "poster_portrait": "poster/portrait/76.webp",
    "poster_landscape": "poster/landscape/76.webp",
    "poster_portrait_fallback": "poster/portrait/76.jpg",
    "poster_landscape_fallback": "poster/landscape/76.jpg"
  },
  {
    "id": 77,
    "title": "Eternals",
    "release_date": "2021-11-05",
    "year": 2021,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 156,
    "watch_time": "2h 36m",
    "rating": "6.3/10",
    "trailer": "https://www.youtube.com/watch?v=0WVDKZJkGlY",
    "tmdb_id": 524434,
    "is_tv": false,
    "ddr_slug": "eternals",
    "poster_portrait": "poster/portrait/77.webp",
    "poster_landscape": "poster/landscape/77.webp",
    "poster_portrait_fallback": "poster/portrait/77.jpg",
    "poster_landscape_fallback": "poster/landscape/77.jpg"
  },
  {
    "id": 78,
    "title": "Hawkeye",
    "release_date": "2021-11-24",
    "year": 2021,
    "type": "series",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 288,
    "total_watch_time": "4h 48m",
    "avg_watch_time": "48m / ep",
    "episodes": 6,
    "rating": "7.5/10",
    "trailer": "https://www.youtube.com/watch?v=5VYb3B1ETlk",
    "tmdb_id": 88329,
    "is_tv": true,
    "ddr_slug": "hawkeye",
    "poster_portrait": "poster/portrait/78.webp",
    "poster_landscape": "poster/landscape/78.webp",
    "poster_portrait_fallback": "poster/portrait/78.jpg",
    "poster_landscape_fallback": "poster/landscape/78.jpg"
  },
  {
    "id": 79,
    "title": "Spider-Man: No Way Home",
    "release_date": "2021-12-17",
    "year": 2021,
    "type": "movie",
    "universe": "MCU/multiverse",
    "category": "MCU",
    "runtime_mins": 148,
    "watch_time": "2h 28m",
    "rating": "8.2/10",
    "trailer": "https://www.youtube.com/watch?v=JfVOs4VSpmA",
    "tmdb_id": 634649,
    "is_tv": false,
    "ddr_slug": "spider-man-no-way-home",
    "poster_portrait": "poster/portrait/79.webp",
    "poster_landscape": "poster/landscape/79.webp",
    "poster_portrait_fallback": "poster/portrait/79.jpg",
    "poster_landscape_fallback": "poster/landscape/79.jpg"
  },
  {
    "id": 80,
    "title": "Moon Knight",
    "release_date": "2022-03-30",
    "year": 2022,
    "type": "series",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 294,
    "total_watch_time": "4h 54m",
    "avg_watch_time": "49m / ep",
    "episodes": 6,
    "rating": "7.3/10",
    "trailer": "https://www.youtube.com/watch?v=x7Krla_UxRg",
    "tmdb_id": 92749,
    "is_tv": true,
    "poster_portrait": "poster/portrait/80.webp",
    "poster_landscape": "poster/landscape/80.webp",
    "poster_portrait_fallback": "poster/portrait/80.jpg",
    "poster_landscape_fallback": "poster/landscape/80.jpg"
  },
  {
    "id": 81,
    "title": "Morbius",
    "release_date": "2022-04-01",
    "year": 2022,
    "type": "movie",
    "universe": "Sony's Spider-Man Universe",
    "category": "Sony",
    "runtime_mins": 104,
    "watch_time": "1h 44m",
    "rating": "5.2/10",
    "trailer": "https://www.youtube.com/watch?v=oZ6iiRrz1SY",
    "tmdb_id": 526896,
    "is_tv": false,
    "poster_portrait": "poster/portrait/81.webp",
    "poster_landscape": "poster/landscape/81.webp",
    "poster_portrait_fallback": "poster/portrait/81.jpg",
    "poster_landscape_fallback": "poster/landscape/81.jpg"
  },
  {
    "id": 82,
    "title": "Doctor Strange in the Multiverse of Madness",
    "release_date": "2022-05-06",
    "year": 2022,
    "type": "movie",
    "universe": "MCU/multiverse",
    "category": "MCU",
    "runtime_mins": 126,
    "watch_time": "2h 06m",
    "rating": "6.9/10",
    "trailer": "https://www.youtube.com/watch?v=aWzlQ2N6qqg",
    "tmdb_id": 453395,
    "is_tv": false,
    "ddr_slug": "doctor-strange-mom",
    "poster_portrait": "poster/portrait/82.webp",
    "poster_landscape": "poster/landscape/82.webp",
    "poster_portrait_fallback": "poster/portrait/82.jpg",
    "poster_landscape_fallback": "poster/landscape/82.jpg"
  },
  {
    "id": 83,
    "title": "Ms. Marvel",
    "release_date": "2022-06-08",
    "year": 2022,
    "type": "series",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 276,
    "total_watch_time": "4h 36m",
    "avg_watch_time": "46m / ep",
    "episodes": 6,
    "rating": "6.3/10",
    "trailer": "https://www.youtube.com/watch?v=m9EX0f6V11Y",
    "tmdb_id": 92782,
    "is_tv": true,
    "ddr_slug": "ms-marvel",
    "poster_portrait": "poster/portrait/83.webp",
    "poster_landscape": "poster/landscape/83.webp",
    "poster_portrait_fallback": "poster/portrait/83.jpg",
    "poster_landscape_fallback": "poster/landscape/83.jpg"
  },
  {
    "id": 84,
    "title": "Thor: Love and Thunder",
    "release_date": "2022-07-08",
    "year": 2022,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 118,
    "watch_time": "1h 58m",
    "rating": "6.2/10",
    "trailer": "https://www.youtube.com/watch?v=Go8nTmfrQd8",
    "tmdb_id": 616037,
    "is_tv": false,
    "ddr_slug": "thor-love-and-thunder",
    "poster_portrait": "poster/portrait/84.webp",
    "poster_landscape": "poster/landscape/84.webp",
    "poster_portrait_fallback": "poster/portrait/84.jpg",
    "poster_landscape_fallback": "poster/landscape/84.jpg"
  },
  {
    "id": 85,
    "title": "I Am Groot \u2014 Season 1",
    "release_date": "2022-08-10",
    "year": 2022,
    "type": "series",
    "universe": "MCU animation",
    "category": "MCU",
    "runtime_mins": 20,
    "total_watch_time": "0h 20m",
    "avg_watch_time": "4m / ep",
    "episodes": 5,
    "rating": "6.7/10",
    "trailer": "https://www.youtube.com/watch?v=D7eFpRf4tac",
    "tmdb_id": 114472,
    "is_tv": true,
    "poster_portrait": "poster/portrait/85.webp",
    "poster_landscape": "poster/landscape/85.webp",
    "poster_portrait_fallback": "poster/portrait/85.jpg",
    "poster_landscape_fallback": "poster/landscape/85.jpg"
  },
  {
    "id": 86,
    "title": "She-Hulk: Attorney at Law",
    "release_date": "2022-08-18",
    "year": 2022,
    "type": "series",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 297,
    "total_watch_time": "4h 57m",
    "avg_watch_time": "33m / ep",
    "episodes": 9,
    "rating": "5.3/10",
    "trailer": "https://www.youtube.com/watch?v=gim2kprjL50",
    "tmdb_id": 92783,
    "is_tv": true,
    "ddr_slug": "she-hulk",
    "poster_portrait": "poster/portrait/86.webp",
    "poster_landscape": "poster/landscape/86.webp",
    "poster_portrait_fallback": "poster/portrait/86.jpg",
    "poster_landscape_fallback": "poster/landscape/86.jpg"
  },
  {
    "id": 87,
    "title": "Werewolf by Night",
    "release_date": "2022-10-07",
    "year": 2022,
    "type": "movie",
    "universe": "Marvel Studios Special",
    "category": "MCU",
    "runtime_mins": 52,
    "watch_time": "0h 52m",
    "rating": "7.1/10",
    "trailer": "https://www.youtube.com/watch?v=bLEFqhS5WmI",
    "tmdb_id": 92782,
    "is_tv": false,
    "poster_portrait": "poster/portrait/87.webp",
    "poster_landscape": "poster/landscape/87.webp",
    "poster_portrait_fallback": "poster/portrait/87.jpg",
    "poster_landscape_fallback": "poster/landscape/87.jpg"
  },
  {
    "id": 88,
    "title": "Black Panther: Wakanda Forever",
    "release_date": "2022-11-11",
    "year": 2022,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 161,
    "watch_time": "2h 41m",
    "rating": "6.7/10",
    "trailer": "https://www.youtube.com/watch?v=_Z3QKfv30tU",
    "tmdb_id": 505642,
    "is_tv": false,
    "ddr_slug": "black-panther-wakanda-forever",
    "poster_portrait": "poster/portrait/88.webp",
    "poster_landscape": "poster/landscape/88.webp",
    "poster_portrait_fallback": "poster/portrait/88.jpg",
    "poster_landscape_fallback": "poster/landscape/88.jpg"
  },
  {
    "id": 89,
    "title": "The Guardians of the Galaxy Holiday Special",
    "release_date": "2022-11-25",
    "year": 2022,
    "type": "movie",
    "universe": "Marvel Studios Special",
    "category": "MCU",
    "runtime_mins": 42,
    "watch_time": "0h 42m",
    "rating": "6.9/10",
    "trailer": "https://www.youtube.com/watch?v=OYhFF_J3gkE",
    "tmdb_id": 774752,
    "is_tv": false,
    "poster_portrait": "poster/portrait/89.webp",
    "poster_landscape": "poster/landscape/89.webp",
    "poster_portrait_fallback": "poster/portrait/89.jpg",
    "poster_landscape_fallback": "poster/landscape/89.jpg"
  },
  {
    "id": 90,
    "title": "Ant-Man and the Wasp: Quantumania",
    "release_date": "2023-02-17",
    "year": 2023,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 124,
    "watch_time": "2h 04m",
    "rating": "6.0/10",
    "trailer": "https://www.youtube.com/watch?v=ZlNFpri-Y40",
    "tmdb_id": 640146,
    "is_tv": false,
    "ddr_slug": "ant-man-quantumania",
    "poster_portrait": "poster/portrait/90.webp",
    "poster_landscape": "poster/landscape/90.webp",
    "poster_portrait_fallback": "poster/portrait/90.jpg",
    "poster_landscape_fallback": "poster/landscape/90.jpg"
  },
  {
    "id": 91,
    "title": "Guardians of the Galaxy Vol. 3",
    "release_date": "2023-05-05",
    "year": 2023,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 150,
    "watch_time": "2h 30m",
    "rating": "7.9/10",
    "trailer": "https://www.youtube.com/watch?v=u3V5KDHRQvk",
    "tmdb_id": 447365,
    "is_tv": false,
    "ddr_slug": "guardians-of-the-galaxy-vol-3",
    "poster_portrait": "poster/portrait/91.webp",
    "poster_landscape": "poster/landscape/91.webp",
    "poster_portrait_fallback": "poster/portrait/91.jpg",
    "poster_landscape_fallback": "poster/landscape/91.jpg"
  },
  {
    "id": 92,
    "title": "Spider-Man: Across the Spider-Verse",
    "release_date": "2023-06-02",
    "year": 2023,
    "type": "movie",
    "universe": "Sony/animated multiverse",
    "category": "Sony",
    "runtime_mins": 140,
    "watch_time": "2h 20m",
    "rating": "8.6/10",
    "trailer": "https://www.youtube.com/watch?v=cqGjhVJWtEg",
    "tmdb_id": 569094,
    "is_tv": false,
    "poster_portrait": "poster/portrait/92.webp",
    "poster_landscape": "poster/landscape/92.webp",
    "poster_portrait_fallback": "poster/portrait/92.jpg",
    "poster_landscape_fallback": "poster/landscape/92.jpg"
  },
  {
    "id": 93,
    "title": "Secret Invasion",
    "release_date": "2023-06-21",
    "year": 2023,
    "type": "series",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 264,
    "total_watch_time": "4h 24m",
    "avg_watch_time": "44m / ep",
    "episodes": 6,
    "rating": "5.9/10",
    "trailer": "https://www.youtube.com/watch?v=Tp_YZNqNBhw",
    "tmdb_id": 114479,
    "is_tv": true,
    "ddr_slug": "secret-invasion",
    "poster_portrait": "poster/portrait/93.webp",
    "poster_landscape": "poster/landscape/93.webp",
    "poster_portrait_fallback": "poster/portrait/93.jpg",
    "poster_landscape_fallback": "poster/landscape/93.jpg"
  },
  {
    "id": 94,
    "title": "I Am Groot \u2014 Season 2",
    "release_date": "2023-09-06",
    "year": 2023,
    "type": "series",
    "universe": "MCU animation",
    "category": "MCU",
    "runtime_mins": 20,
    "total_watch_time": "0h 20m",
    "avg_watch_time": "4m / ep",
    "episodes": 5,
    "rating": "6.5/10",
    "trailer": "https://www.youtube.com/watch?v=1d977_k8s3s",
    "tmdb_id": 114472,
    "is_tv": true,
    "poster_portrait": "poster/portrait/94.webp",
    "poster_landscape": "poster/landscape/94.webp",
    "poster_portrait_fallback": "poster/portrait/94.jpg",
    "poster_landscape_fallback": "poster/landscape/94.jpg"
  },
  {
    "id": 95,
    "title": "Loki \u2014 Season 2",
    "release_date": "2023-10-05",
    "year": 2023,
    "type": "series",
    "universe": "TVA / multiverse",
    "category": "MCU",
    "runtime_mins": 306,
    "total_watch_time": "5h 06m",
    "avg_watch_time": "51m / ep",
    "episodes": 6,
    "rating": "8.2/10",
    "trailer": "https://www.youtube.com/watch?v=dug56u8NN7g",
    "tmdb_id": 84958,
    "is_tv": true,
    "ddr_slug": "loki-s2",
    "poster_portrait": "poster/portrait/95.webp",
    "poster_landscape": "poster/landscape/95.webp",
    "poster_portrait_fallback": "poster/portrait/95.jpg",
    "poster_landscape_fallback": "poster/landscape/95.jpg"
  },
  {
    "id": 96,
    "title": "The Marvels",
    "release_date": "2023-11-10",
    "year": 2023,
    "type": "movie",
    "universe": "MCU / multiverse setup",
    "category": "MCU",
    "runtime_mins": 105,
    "watch_time": "1h 45m",
    "rating": "5.5/10",
    "trailer": "https://www.youtube.com/watch?v=wS_qbD02650",
    "tmdb_id": 609681,
    "is_tv": false,
    "ddr_slug": "the-marvels",
    "poster_portrait": "poster/portrait/96.webp",
    "poster_landscape": "poster/landscape/96.webp",
    "poster_portrait_fallback": "poster/portrait/96.jpg",
    "poster_landscape_fallback": "poster/landscape/96.jpg"
  },
  {
    "id": 97,
    "title": "What If...? \u2014 Season 2",
    "release_date": "2023-12-22",
    "year": 2023,
    "type": "series",
    "universe": "Animated multiverse",
    "category": "MCU",
    "runtime_mins": 288,
    "total_watch_time": "4h 48m",
    "avg_watch_time": "32m / ep",
    "episodes": 9,
    "rating": "7.3/10",
    "trailer": "https://www.youtube.com/watch?v=TiEV_b3aTmA",
    "tmdb_id": 91363,
    "is_tv": true,
    "poster_portrait": "poster/portrait/97.webp",
    "poster_landscape": "poster/landscape/97.webp",
    "poster_portrait_fallback": "poster/portrait/97.jpg",
    "poster_landscape_fallback": "poster/landscape/97.jpg"
  },
  {
    "id": 98,
    "title": "Echo",
    "release_date": "2024-01-09",
    "year": 2024,
    "type": "series",
    "universe": "MCU/Defenders",
    "category": "MCU",
    "runtime_mins": 210,
    "total_watch_time": "3h 30m",
    "avg_watch_time": "42m / ep",
    "episodes": 5,
    "rating": "6.0/10",
    "trailer": "https://www.youtube.com/watch?v=AFUKnherhuw",
    "tmdb_id": 138502,
    "is_tv": true,
    "ddr_slug": "echo",
    "poster_portrait": "poster/portrait/98.webp",
    "poster_landscape": "poster/landscape/98.webp",
    "poster_portrait_fallback": "poster/portrait/98.jpg",
    "poster_landscape_fallback": "poster/landscape/98.jpg"
  },
  {
    "id": 99,
    "title": "Madame Web",
    "release_date": "2024-02-14",
    "year": 2024,
    "type": "movie",
    "universe": "Sony's Spider-Man Universe",
    "category": "Sony",
    "runtime_mins": 116,
    "watch_time": "1h 56m",
    "rating": "4.0/10",
    "trailer": "https://www.youtube.com/watch?v=s_76M4c4LTo",
    "tmdb_id": 634492,
    "is_tv": false,
    "poster_portrait": "poster/portrait/99.webp",
    "poster_landscape": "poster/landscape/99.webp",
    "poster_portrait_fallback": "poster/portrait/99.jpg",
    "poster_landscape_fallback": "poster/landscape/99.jpg"
  },
  {
    "id": 100,
    "title": "X-Men '97 \u2014 Season 1",
    "release_date": "2024-03-20",
    "year": 2024,
    "type": "series",
    "universe": "Animated multiverse/Fox legacy",
    "category": "Fox",
    "runtime_mins": 320,
    "total_watch_time": "5h 20m",
    "avg_watch_time": "32m / ep",
    "episodes": 10,
    "rating": "8.8/10",
    "trailer": "https://www.youtube.com/watch?v=pv3Ss8o9au4",
    "tmdb_id": 138503,
    "is_tv": true,
    "poster_portrait": "poster/portrait/100.webp",
    "poster_landscape": "poster/landscape/100.webp",
    "poster_portrait_fallback": "poster/portrait/100.jpg",
    "poster_landscape_fallback": "poster/landscape/100.jpg"
  },
  {
    "id": 101,
    "title": "Deadpool & Wolverine",
    "release_date": "2024-07-26",
    "year": 2024,
    "type": "movie",
    "universe": "Major multiverse crossover",
    "category": "MCU",
    "runtime_mins": 128,
    "watch_time": "2h 08m",
    "rating": "7.7/10",
    "trailer": "https://www.youtube.com/watch?v=73_1biulkYk",
    "tmdb_id": 533535,
    "is_tv": false,
    "ddr_slug": "deadpool-wolverine",
    "poster_portrait": "poster/portrait/101.webp",
    "poster_landscape": "poster/landscape/101.webp",
    "poster_portrait_fallback": "poster/portrait/101.jpg",
    "poster_landscape_fallback": "poster/landscape/101.jpg"
  },
  {
    "id": 102,
    "title": "Agatha All Along",
    "release_date": "2024-09-18",
    "year": 2024,
    "type": "series",
    "universe": "MCU/magic",
    "category": "MCU",
    "runtime_mins": 387,
    "total_watch_time": "6h 27m",
    "avg_watch_time": "43m / ep",
    "episodes": 9,
    "rating": "7.2/10",
    "trailer": "https://www.youtube.com/watch?v=R9pXbFZq82M",
    "tmdb_id": 138501,
    "is_tv": true,
    "poster_portrait": "poster/portrait/102.webp",
    "poster_landscape": "poster/landscape/102.webp",
    "poster_portrait_fallback": "poster/portrait/102.jpg",
    "poster_landscape_fallback": "poster/landscape/102.jpg"
  },
  {
    "id": 103,
    "title": "Venom: The Last Dance",
    "release_date": "2024-10-25",
    "year": 2024,
    "type": "movie",
    "universe": "Sony's Spider-Man Universe",
    "category": "Sony",
    "runtime_mins": 110,
    "watch_time": "1h 50m",
    "rating": "6.1/10",
    "trailer": "https://www.youtube.com/watch?v=__2bjWbetsA",
    "tmdb_id": 912649,
    "is_tv": false,
    "poster_portrait": "poster/portrait/103.webp",
    "poster_landscape": "poster/landscape/103.webp",
    "poster_portrait_fallback": "poster/portrait/103.jpg",
    "poster_landscape_fallback": "poster/landscape/103.jpg"
  },
  {
    "id": 104,
    "title": "Kraven the Hunter",
    "release_date": "2024-12-13",
    "year": 2024,
    "type": "movie",
    "universe": "Sony's Spider-Man Universe",
    "category": "Sony",
    "runtime_mins": 127,
    "watch_time": "2h 07m",
    "rating": "5.7/10",
    "trailer": "https://www.youtube.com/watch?v=rze8QYwWGMs",
    "tmdb_id": 583152,
    "is_tv": false,
    "poster_portrait": "poster/portrait/104.webp",
    "poster_landscape": "poster/landscape/104.webp",
    "poster_portrait_fallback": "poster/portrait/104.jpg",
    "poster_landscape_fallback": "poster/landscape/104.jpg"
  },
  {
    "id": 105,
    "title": "What If...? \u2014 Season 3",
    "release_date": "2024-12-22",
    "year": 2024,
    "type": "series",
    "universe": "Animated multiverse",
    "category": "MCU",
    "runtime_mins": 264,
    "total_watch_time": "4h 24m",
    "avg_watch_time": "33m / ep",
    "episodes": 8,
    "rating": "7.2/10",
    "trailer": "https://www.youtube.com/watch?v=2nQj71i_1C0",
    "tmdb_id": 91363,
    "is_tv": true,
    "poster_portrait": "poster/portrait/105.webp",
    "poster_landscape": "poster/landscape/105.webp",
    "poster_portrait_fallback": "poster/portrait/105.jpg",
    "poster_landscape_fallback": "poster/landscape/105.jpg"
  },
  {
    "id": 106,
    "title": "Your Friendly Neighborhood Spider-Man \u2014 Season 1",
    "release_date": "2025-01-29",
    "year": 2025,
    "type": "series",
    "universe": "Animated alternate universe",
    "category": "MCU",
    "runtime_mins": 300,
    "total_watch_time": "5h 00m",
    "avg_watch_time": "30m / ep",
    "episodes": 10,
    "rating": "7.4/10",
    "trailer": "https://www.youtube.com/watch?v=2gQG_j8h1C4",
    "tmdb_id": 138505,
    "is_tv": true,
    "poster_portrait": "poster/portrait/106.webp",
    "poster_landscape": "poster/landscape/106.webp",
    "poster_portrait_fallback": "poster/portrait/106.jpg",
    "poster_landscape_fallback": "poster/landscape/106.jpg"
  },
  {
    "id": 107,
    "title": "Captain America: Brave New World",
    "release_date": "2025-02-14",
    "year": 2025,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 118,
    "watch_time": "1h 58m",
    "rating": "6.8/10",
    "trailer": "https://www.youtube.com/watch?v=1pHDWnXmK7Y",
    "tmdb_id": 822119,
    "is_tv": false,
    "ddr_slug": "captain-america-brave-new-world",
    "poster_portrait": "poster/portrait/107.webp",
    "poster_landscape": "poster/landscape/107.webp",
    "poster_portrait_fallback": "poster/portrait/107.jpg",
    "poster_landscape_fallback": "poster/landscape/107.jpg"
  },
  {
    "id": 108,
    "title": "Daredevil: Born Again \u2014 Season 1",
    "release_date": "2025-03-04",
    "year": 2025,
    "type": "series",
    "universe": "MCU/Defenders",
    "category": "Defenders",
    "runtime_mins": 450,
    "total_watch_time": "7h 30m",
    "avg_watch_time": "50m / ep",
    "episodes": 9,
    "rating": "8.4/10",
    "trailer": "https://www.youtube.com/watch?v=7xAXi8Lpnhc",
    "tmdb_id": 202250,
    "is_tv": true,
    "ddr_slug": "daredevil-born-again",
    "poster_portrait": "poster/portrait/108.webp",
    "poster_landscape": "poster/landscape/108.webp",
    "poster_portrait_fallback": "poster/portrait/108.jpg",
    "poster_landscape_fallback": "poster/landscape/108.jpg"
  },
  {
    "id": 109,
    "title": "Thunderbolts*",
    "release_date": "2025-05-02",
    "year": 2025,
    "type": "movie",
    "universe": "MCU / New Avengers",
    "category": "MCU",
    "runtime_mins": 130,
    "watch_time": "2h 10m",
    "rating": "7.2/10",
    "trailer": "https://www.youtube.com/watch?v=-sAOWhvheKc",
    "tmdb_id": 986056,
    "is_tv": false,
    "ddr_slug": "thunderbolts",
    "poster_portrait": "poster/portrait/109.webp",
    "poster_landscape": "poster/landscape/109.webp",
    "poster_portrait_fallback": "poster/portrait/109.jpg",
    "poster_landscape_fallback": "poster/landscape/109.jpg"
  },
  {
    "id": 110,
    "title": "Ironheart",
    "release_date": "2025-06-24",
    "year": 2025,
    "type": "series",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 270,
    "total_watch_time": "4h 30m",
    "avg_watch_time": "45m / ep",
    "episodes": 6,
    "rating": "6.8/10",
    "trailer": "https://www.youtube.com/watch?v=5U9Yk5bT9s8",
    "tmdb_id": 114478,
    "is_tv": true,
    "ddr_slug": "ironheart",
    "poster_portrait": "poster/portrait/110.webp",
    "poster_landscape": "poster/landscape/110.webp",
    "poster_portrait_fallback": "poster/portrait/110.jpg",
    "poster_landscape_fallback": "poster/landscape/110.jpg"
  },
  {
    "id": 111,
    "title": "The Fantastic Four: First Steps",
    "release_date": "2025-07-25",
    "year": 2025,
    "type": "movie",
    "universe": "Earth-828 / major Doomsday universe",
    "category": "MCU",
    "runtime_mins": 135,
    "watch_time": "2h 15m",
    "rating": "7.8/10",
    "trailer": "https://www.youtube.com/watch?v=e_sQ_y0PqR0",
    "tmdb_id": 617127,
    "is_tv": false,
    "ddr_slug": "fantastic-four-first-steps",
    "poster_portrait": "poster/portrait/111.webp",
    "poster_landscape": "poster/landscape/111.webp",
    "poster_portrait_fallback": "poster/portrait/111.jpg",
    "poster_landscape_fallback": "poster/landscape/111.jpg"
  },
  {
    "id": 112,
    "title": "Eyes of Wakanda",
    "release_date": "2025-08-01",
    "year": 2025,
    "type": "series",
    "universe": "Marvel Animation/MCU history",
    "category": "MCU",
    "runtime_mins": 140,
    "total_watch_time": "2h 20m",
    "avg_watch_time": "35m / ep",
    "episodes": 4,
    "rating": "7.0/10",
    "trailer": "https://www.youtube.com/watch?v=8bY7r2_jV9s",
    "tmdb_id": 242099,
    "is_tv": true,
    "poster_portrait": "poster/portrait/112.webp",
    "poster_landscape": "poster/landscape/112.webp",
    "poster_portrait_fallback": "poster/portrait/112.jpg",
    "poster_landscape_fallback": "poster/landscape/112.jpg"
  },
  {
    "id": 113,
    "title": "Marvel Zombies",
    "release_date": "2025-09-24",
    "year": 2025,
    "type": "series",
    "universe": "Animated multiverse",
    "category": "MCU",
    "runtime_mins": 140,
    "total_watch_time": "2h 20m",
    "avg_watch_time": "35m / ep",
    "episodes": 4,
    "rating": "7.2/10",
    "trailer": "https://www.youtube.com/watch?v=W0q_c3P6J5w",
    "tmdb_id": 138506,
    "is_tv": true,
    "poster_portrait": "poster/portrait/113.webp",
    "poster_landscape": "poster/landscape/113.webp",
    "poster_portrait_fallback": "poster/portrait/113.jpg",
    "poster_landscape_fallback": "poster/landscape/113.jpg"
  },
  {
    "id": 114,
    "title": "Wonder Man \u2014 Season 1",
    "release_date": "2026-01-27",
    "year": 2026,
    "type": "series",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 280,
    "total_watch_time": "4h 40m",
    "avg_watch_time": "35m / ep",
    "episodes": 8,
    "rating": "7.0/10",
    "trailer": "https://www.youtube.com/watch?v=e8R4_b_Vz-A",
    "tmdb_id": 204541,
    "is_tv": true,
    "poster_portrait": "poster/portrait/114.webp",
    "poster_landscape": "poster/landscape/114.webp",
    "poster_portrait_fallback": "poster/portrait/114.jpg",
    "poster_landscape_fallback": "poster/landscape/114.jpg"
  },
  {
    "id": 115,
    "title": "Daredevil: Born Again \u2014 Season 2",
    "release_date": "2026-03-24",
    "year": 2026,
    "type": "series",
    "universe": "MCU/Defenders",
    "category": "Defenders",
    "runtime_mins": 450,
    "total_watch_time": "7h 30m",
    "avg_watch_time": "50m / ep",
    "episodes": 9,
    "rating": "8.5/10",
    "trailer": "https://www.youtube.com/watch?v=7xAXi8Lpnhc",
    "tmdb_id": 202250,
    "is_tv": true,
    "poster_portrait": "poster/portrait/115.webp",
    "poster_landscape": "poster/landscape/115.webp",
    "poster_portrait_fallback": "poster/portrait/115.jpg",
    "poster_landscape_fallback": "poster/landscape/115.jpg"
  },
  {
    "id": 116,
    "title": "The Punisher: One Last Kill",
    "release_date": "2026-05-12",
    "year": 2026,
    "type": "movie",
    "universe": "MCU/Defenders",
    "category": "Defenders",
    "runtime_mins": 120,
    "watch_time": "2h 00m",
    "rating": "8.0/10",
    "trailer": "https://www.youtube.com/watch?v=OMW_dP695Jg",
    "tmdb_id": 67178,
    "is_tv": false,
    "poster_portrait": "poster/portrait/116.webp",
    "poster_landscape": "poster/landscape/116.webp",
    "poster_portrait_fallback": "poster/portrait/116.jpg",
    "poster_landscape_fallback": "poster/landscape/116.jpg"
  },
  {
    "id": 117,
    "title": "X-Men '97 \u2014 Season 2",
    "release_date": "2026-07-01",
    "year": 2026,
    "type": "series",
    "universe": "Animated multiverse/Fox legacy",
    "category": "Fox",
    "runtime_mins": 320,
    "total_watch_time": "5h 20m",
    "avg_watch_time": "32m / ep",
    "episodes": 10,
    "rating": "8.7/10",
    "trailer": "https://www.youtube.com/watch?v=pv3Ss8o9au4",
    "tmdb_id": 138503,
    "is_tv": true,
    "poster_portrait": "poster/portrait/117.webp",
    "poster_landscape": "poster/landscape/117.webp",
    "poster_portrait_fallback": "poster/portrait/117.jpg",
    "poster_landscape_fallback": "poster/landscape/117.jpg"
  },
  {
    "id": 118,
    "title": "Spider-Man: Brand New Day",
    "release_date": "2026-07-31",
    "year": 2026,
    "type": "movie",
    "universe": "MCU",
    "category": "MCU",
    "runtime_mins": 135,
    "watch_time": "2h 15m",
    "rating": "8.0/10",
    "trailer": "https://www.youtube.com/watch?v=JfVOs4VSpmA",
    "tmdb_id": 429617,
    "is_tv": false,
    "ddr_slug": "spider-man-brand-new-day",
    "poster_portrait": "poster/portrait/118.webp",
    "poster_landscape": "poster/landscape/118.webp",
    "poster_portrait_fallback": "poster/portrait/118.jpg",
    "poster_landscape_fallback": "poster/landscape/118.jpg"
  },
  {
    "id": 119,
    "title": "Avengers: Endgame Encore",
    "release_date": "2026-09-25",
    "year": 2026,
    "type": "movie",
    "universe": "Doomsday bridge",
    "category": "MCU",
    "runtime_mins": 190,
    "watch_time": "3h 10m",
    "rating": "8.6/10",
    "trailer": "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    "tmdb_id": 299534,
    "is_tv": false,
    "poster_portrait": "poster/portrait/119.webp",
    "poster_landscape": "poster/landscape/119.webp",
    "poster_portrait_fallback": "poster/portrait/119.jpg",
    "poster_landscape_fallback": "poster/landscape/119.jpg"
  },
  {
    "id": 120,
    "title": "VisionQuest",
    "release_date": "2026-10-14",
    "year": 2026,
    "type": "series",
    "universe": "MCU / WandaVision storyline",
    "category": "MCU",
    "runtime_mins": 270,
    "total_watch_time": "4h 30m",
    "avg_watch_time": "45m / ep",
    "episodes": 6,
    "rating": "7.3/10",
    "trailer": "https://www.youtube.com/watch?v=UBhlqe2KVt4",
    "tmdb_id": 85271,
    "is_tv": true,
    "ddr_slug": "visionquest",
    "poster_portrait": "poster/portrait/120.webp",
    "poster_landscape": "poster/landscape/120.webp",
    "poster_portrait_fallback": "poster/portrait/120.jpg",
    "poster_landscape_fallback": "poster/landscape/120.jpg"
  },
  {
    "id": 121,
    "title": "Avengers: Doomsday",
    "release_date": "2026-12-18",
    "year": 2026,
    "type": "movie",
    "universe": "END",
    "category": "MCU",
    "runtime_mins": 165,
    "watch_time": "2h 45m",
    "rating": "Anticipated",
    "trailer": "https://www.youtube.com/watch?v=y3Yj6jF2b28",
    "tmdb_id": 1003596,
    "is_tv": false,
    "ddr_slug": "avengers-doomsday",
    "poster_portrait": "poster/portrait/121.webp",
    "poster_landscape": "poster/landscape/121.webp",
    "poster_portrait_fallback": "poster/portrait/121.jpg",
    "poster_landscape_fallback": "poster/landscape/121.jpg"
  }
];
